Feature/1/database
Cruder/school_planner_old pull request #9
Opened 2017-09-11 13:37 UTC by amelie-certin

2017-09-17 16:12 UTC, alex-lairan requested changes
Rebase, you have devise commit

2017-09-17 16:12 UTC, alex-lairan commented on app/models/classrooms_user.rb
> +
Presence of `as`

2017-09-17 16:12 UTC, alex-lairan commented on app/models/classroom.rb
> +  }, unless: proc { |classroom| classroom.school_id.nil? }
It could be `if: :classroom` no?

2017-09-17 16:12 UTC, alex-lairan commented on app/models/homeworks_user.rb
> +
Presence of `progress`

2017-12-26 12:27 UTC, amelie-certin commented
Cette branche est encore utile ?

2017-12-26 12:28 UTC, alex-lairan commented
Je ne pense pas

2017-12-27 15:01 UTC, closed without merging